[package]
org = "ballerinax"
name = "mongodb"
version = "2.0.10"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["MongoDB", "NoSQL"]
repository = "https://github.com/lakshanss/module-lakshans-mongodb"

[[platform.java11.dependency]]
path = "../mongodb-native/build/libs/mongodb-native-2.0.10-all.jar"
groupId = "org.ballerinalang"
artifactId = "mongodb-native"
version = "2.0.10"
